"""Apply human_labels to labeled_mentions.jsonl for all arctic_shift entries."""
import json
from pathlib import Path

FIXTURE = Path("backend/tests/fixtures/extractor/labeled_mentions.jsonl")

# All derived labels for arctic_shift entries.
# IDs not in this dict keep their existing human_labels (i.e., seeds stay intact).
LABELS: dict[str, list] = {
    # ── lines 31-100 ──────────────────────────────────────────────
    # investing
    "1tcfvel": [],
    "1tcfkf0": [],
    "1tcfk12": [{"ticker": "MU", "sentiment": "bullish"}],
    "1tcfcm4": [],
    "1tcehic": [],
    "1tcc4n1": [],
    "1tcaik8": [],
    "1tca8vf": [],
    "1tc8dpi": [],
    "1tc8d6j": [],
    "1tc7qku": [],
    "1tc6wgc": [{"ticker": "SMCI", "sentiment": "bullish"}],
    "1tc62op": [],
    "1tc61lg": [],
    "1tc5sia": [],
    "1tc5bp7": [],
    "1tc470j": [],
    "1tc344s": [],
    "1tc2y9j": [],
    "1tc2u95": [],
    "1tc2gh2": [],
    "1tc2c9y": [],
    "1tc264q": [],
    # stocks
    "1tcfm8u": [{"ticker": "MU", "sentiment": "bullish"}],
    "1tcdjda": [],
    "1tccn5s": [],
    "1tcaz6s": [],
    "1tc9zrl": [],
    "1tc9lka": [],
    "1tc8jae": [{"ticker": "CASY", "sentiment": "bullish"}],
    "1tc8fg1": [],
    "1tc73ot": [{"ticker": "SPCE", "sentiment": "bullish"}],
    # SecurityAnalysis
    "1tce5cr": [],
    "1tc3pbe": [],
    "1t7w6wd": [],
    "1t7w66z": [],
    "1t4g2sz": [],
    "1t40qad": [],
    "1t2qv5f": [],
    "1sz1kpb": [{"ticker": "JET2", "sentiment": "bullish"}],
    # ValueInvesting
    "1tcgjr3": [],
    "1tcfzr3": [{"ticker": "PATH", "sentiment": "bullish"}],
    "1tcfifu": [{"ticker": "MU", "sentiment": "bullish"}],
    "1tcf2t2": [],
    "1tcdgr1": [{"ticker": "KHC", "sentiment": "bullish"}],
    "1tcdg93": [],
    "1tcd7w5": [{"ticker": "REI", "sentiment": "bullish"}],
    "1tccu8v": [],
    "1tccofc": [],
    "1tcc27j": [],
    "1tcc180": [],
    "1tcbo4v": [{"ticker": "MSFT", "sentiment": "bearish"}],
    "1tcajgw": [{"ticker": "VTY", "sentiment": "bullish"}],
    "1tcaeab": [],
    "1tca2f6": [{"ticker": "MSFT", "sentiment": "bearish"}],
    "1tc9kfl": [{"ticker": "CHTR", "sentiment": "bullish"}],
    "1tc9d22": [{"ticker": "GOOGL", "sentiment": "bullish"}],
    # wallstreetbets
    "1tcgioq": [],
    "1tcgesq": [{"ticker": "NOK", "sentiment": "bullish"}],
    "1tcg8ga": [],
    "1tcfa8c": [],
    "1tcf5y3": [],
    "1tcczyw": [{"ticker": "NOK", "sentiment": "bullish"}],
    # options
    "1tcf4ly": [],
    "1tccbyl": [],
    "1tcc9kx": [],
    "1tcah7p": [],
    "1tca5k1": [{"ticker": "SOFI", "sentiment": "bullish"}],
    "1tca215": [],
    "1tc9cjp": [],

    # ── lines 101-200 ─────────────────────────────────────────────
    # options
    "1tc9cfi": [],
    "1tc8zu5": [],
    "1tc5he9": [],
    "1tc36se": [],
    "1tc0c5g": [],
    "1tbykvc": [],
    "1tbxxsx": [],
    "1tbkcop": [],
    "1tbjgx5": [],
    "1tbipzq": [],
    "1tbi071": [],
    "1tbg1bd": [{"ticker": "VRT", "sentiment": "bearish"}],
    "1tbex65": [],
    "1tbel7a": [],
    "1tbdgfs": [],
    "1tbbxne": [{"ticker": "SATS", "sentiment": "bullish"}],
    # smallstreetbets
    "1tcg2ew": [],
    "1tcf7kg": [{"ticker": "HMR", "sentiment": "bullish"}],
    "1tcf4j8": [],
    "1tcejve": [],
    "1tce32x": [{"ticker": "QUCY", "sentiment": "bullish"}],
    "1tcdl5w": [],
    "1tcddqp": [],
    "1tcd79d": [{"ticker": "REI", "sentiment": "bullish"}],
    # artificial
    "1tcf0wr": [],
    "1tcd3dp": [],
    "1tcbvwx": [],
    "1tcbm8i": [],
    "1tc9g3v": [],
    "1tc9e62": [],
    "1tc8xxj": [],
    # Semiconductors
    "1tccwhc": [],
    "1tc5kgo": [],
    "1tbxhql": [],
    "1tbx5kj": [],
    "1tbu4ap": [],
    "1tbu3s3": [],
    "1tbqgfv": [],
    "1tbmr9i": [],
    "1tbhqiq": [],
    "1tb2k9h": [],
    "1tb2grs": [],
    # energy
    "1tcgkio": [],
    "1tc9q4k": [],
    "1tc5puu": [],
    "1tc4qil": [],
    "1tc1dur": [],
    # investing (continued)
    "1tc1skq": [],
    "1tc18hn": [{"ticker": "WIX", "sentiment": "bullish"}],
    "1tc13k7": [],
    "1tc0szl": [],
    "1tc0lve": [],
    "1tc0krb": [],
    "1tc082i": [{"ticker": "ARKF", "sentiment": "bullish"}],
    "1tbz37k": [],
    "1tbx4v4": [{"ticker": "DXYZ", "sentiment": "bearish"}],
    "1tbwnog": [],
    "1tbw3ov": [],
    "1tbw2qs": [],
    "1tbw1kb": [],
    "1tbvp38": [{"ticker": "IALT", "sentiment": "bullish"}],
    "1tbvgam": [],
    "1tbsz0t": [],
    "1tbrind": [],
    "1tbre9z": [],
    "1tbo11t": [
        {"ticker": "SLS", "sentiment": "bullish"},
        {"ticker": "CGON", "sentiment": "bullish"},
        {"ticker": "COGT", "sentiment": "bullish"},
        {"ticker": "SMMT", "sentiment": "bullish"},
    ],
    "1tbihcw": [],
    "1tbi9jb": [{"ticker": "RHM", "sentiment": "bullish"}],
    "1tbhx28": [],
    "1tbhmyp": [{"ticker": "REKR", "sentiment": "bullish"}],
    "1tbev7e": [],
    "1tbcgep": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tbaijw": [],
    "1tb96v0": [{"ticker": "RDDT", "sentiment": "bullish"}],
    "1tb8xiu": [],
    "1tb8u2f": [],
    "1tb8kfp": [],
    "1tb63nb": [],
    "1tb5x6z": [{"ticker": "NVDA", "sentiment": "bearish"}],
    "1tb5x5f": [],
    "1tb4fge": [],
    "1tb41sf": [],
    "1tb3edm": [],
    "1tb30bp": [
        {"ticker": "ALMU", "sentiment": "bullish"},
        {"ticker": "POET", "sentiment": "bullish"},
    ],
    "1tb2hin": [],
    "1tb1tk1": [],
    "1tb1q0j": [
        {"ticker": "INTC", "sentiment": "bearish"},
        {"ticker": "AMD", "sentiment": "bearish"},
        {"ticker": "AMZN", "sentiment": "bearish"},
    ],
    "1tb1ccg": [],
    "1tb17u8": [],
    "1tay3a4": [],
    "1tawuxh": [{"ticker": "EUV", "sentiment": "bullish"}],
    "1taw0n5": [],
    "1tavw0n": [{"ticker": "EUV", "sentiment": "bullish"}],
    "1tavu1a": [{"ticker": "BREW", "sentiment": "bullish"}],
    "1tavitj": [],
    "1tavdd0": [],
    "1tav6bi": [{"ticker": "WR", "sentiment": "bullish"}],
    "1tauuey": [],
    "1taulvd": [
        {"ticker": "INTC", "sentiment": "bullish"},
        {"ticker": "AMD", "sentiment": "bullish"},
        {"ticker": "TSM", "sentiment": "bullish"},
    ],
    "1taucyi": [{"ticker": "UPST", "sentiment": "bullish"}],

    # ── lines 201-500 (from session summary) ─────────────────────
    # investing / stocks / SecurityAnalysis / ValueInvesting batches
    "1tau7sv": [{"ticker": "EUV", "sentiment": "bullish"}],
    "1tatxfb": [{"ticker": "KYC", "sentiment": "bullish"}],
    "1tathpq": [{"ticker": "BREW", "sentiment": "bullish"}],
    "1tasq4s": [{"ticker": "WATS", "sentiment": "bullish"}],
    "1tasha3": [],
    "1tas8e1": [{"ticker": "EUV", "sentiment": "bullish"}],
    "1tarz8w": [],
    "1taq7kk": [{"ticker": "PLAB", "sentiment": "bullish"}],
    "1taoj02": [],
    "1taoh8t": [],
    "1tao45k": [{"ticker": "QMY", "sentiment": "bullish"}],
    "1tanqiu": [{"ticker": "EUV", "sentiment": "bullish"}],
    "1tam3hd": [],
    "1taltvz": [{"ticker": "ARKK", "sentiment": "bearish"}],
    "1tahp97": [],
    "1tah0ur": [],
    "1tagzsv": [],
    "1tagpgf": [],
    "1taghtf": [{"ticker": "EUV", "sentiment": "bullish"}],
    "1tafokl": [],
    "1tc6fht": [],
    "1tc6bkr": [{"ticker": "QUCY", "sentiment": "bearish"}],
    "1tc6bc3": [{"ticker": "NB", "sentiment": "bullish"}],
    "1tc5tc4": [],
    "1tc572c": [],
    "1tc53bs": [],
    "1tc3vww": [],
    "1tc32h2": [{"ticker": "GOOG", "sentiment": "bullish"}],
    "1tc2vm4": [],
    "1tc2fbu": [{"ticker": "FLEX", "sentiment": "bullish"}],
    "1tc14hi": [],
    "1tc0z0o": [],
    "1tc0qxe": [],
    "1tc0ngj": [],
    "1tc0eii": [{"ticker": "ABT", "sentiment": "bullish"}],
    "1tc00tp": [{"ticker": "DRTS", "sentiment": "bullish"}],
    "1tbytz2": [],
    "1tby9dh": [],
    "1tbx80v": [],
    "1tbx1dz": [{"ticker": "NBIS", "sentiment": "bullish"}],
    "1tbwwiz": [{"ticker": "CHTR", "sentiment": "bearish"}],
    "1tbwqxd": [],
    "1tbvi2n": [],
    "1tbvb7h": [],
    "1tbv3wi": [],
    "1tbufrn": [],
    "1tbtcuf": [],
    "1tbt5h3": [{"ticker": "NVDA", "sentiment": "bullish"}],
    "1tbsk3d": [{"ticker": "SE", "sentiment": "bullish"}],
    "1tbryb8": [],
    "1tbqksj": [],
    "1tbprus": [{"ticker": "RMD", "sentiment": "bullish"}],
    "1tbo6ki": [],
    "1tbo00c": [{"ticker": "BB", "sentiment": "bullish"}],
    "1tbnymv": [
        {"ticker": "SLS", "sentiment": "bullish"},
        {"ticker": "CGON", "sentiment": "bullish"},
        {"ticker": "COGT", "sentiment": "bullish"},
        {"ticker": "SMMT", "sentiment": "bullish"},
    ],
    "1tbmi3j": [],
    "1tbm211": [{"ticker": "MU", "sentiment": "bullish"}],
    "1tbl57s": [{"ticker": "CHTR", "sentiment": "bullish"}],
    "1tbkz0h": [],
    "1tbk8qm": [],
    "1tbh396": [],
    "1tbgzpw": [],
    "1tbgvwi": [],
    "1tbflui": [],
    "1tbf513": [],
    "1tbdvhp": [],
    "1tbdoww": [{"ticker": "TOST", "sentiment": "bullish"}],
    "1tbcu95": [],
    "1tbc910": [],
    "1tbc8d6": [],
    "1tbc5w7": [],
    "1tbbxq0": [{"ticker": "UBER", "sentiment": "bullish"}],
    "1tbauw1": [
        {"ticker": "ASML", "sentiment": "bullish"},
        {"ticker": "ETN", "sentiment": "bullish"},
    ],
    "1tba7yl": [],
    "1tb9tic": [{"ticker": "AMZN", "sentiment": "bullish"}],
    "1tb9ozs": [{"ticker": "BWEN", "sentiment": "bullish"}],
    "1tb9c65": [],
    "1tb8zcm": [{"ticker": "DRTS", "sentiment": "bullish"}],
    # SecurityAnalysis
    "1spxq9l": [],
    "1sn6005": [{"ticker": "PLOW", "sentiment": "bullish"}],
    "1skc5ah": [],
    "1shn446": [{"ticker": "AMZN", "sentiment": "bullish"}],
    "1s6x0kd": [{"ticker": "BLND", "sentiment": "bullish"}],
    "1rx3ctn": [{"ticker": "ADBE", "sentiment": "bullish"}],
    "1reqqz9": [{"ticker": "RDDT", "sentiment": "bullish"}],
    "1qwa5z9": [{"ticker": "MLR", "sentiment": "bullish"}],
    "1qu7oni": [
        {"ticker": "CAT", "sentiment": "bullish"},
        {"ticker": "WIX", "sentiment": "bullish"},
    ],
    "1qkjcv3": [{"ticker": "DUOL", "sentiment": "bullish"}],
    "1q8hgc7": [],
    "1q7e0zc": [{"ticker": "TDS", "sentiment": "bullish"}],
    "1q5ylso": [],
    "1q3ip4w": [{"ticker": "VSNT", "sentiment": "bullish"}],
    "1q2y8oo": [],
    "1q1hkq4": [],
    "1pqm9ow": [],
    "1pnwpdh": [{"ticker": "META", "sentiment": "bullish"}],
    "1pmggse": [],
    "1pgm5cp": [{"ticker": "GLIBA", "sentiment": "bullish"}],
    "1pg5hbx": [],
    "1p6zyvh": [],
    "1p59bjv": [{"ticker": "PDD", "sentiment": "bullish"}],
    "1p1xz5y": [{"ticker": "MSCI", "sentiment": "bullish"}],
    "1oz12ot": [],
    "1otml1x": [{"ticker": "CCC", "sentiment": "bullish"}],
    "1ori9x2": [],
    "1oqnv1s": [],
    # ValueInvesting
    "1tc9b1t": [],
    "1tc7a75": [
        {"ticker": "BR", "sentiment": "bullish"},
        {"ticker": "RELX", "sentiment": "bullish"},
    ],
    "1tc63tf": [],
    "1tc5zq9": [
        {"ticker": "ACN", "sentiment": "bullish"},
        {"ticker": "CTSH", "sentiment": "bullish"},
    ],
    "1tc5muo": [{"ticker": "TME", "sentiment": "bullish"}],
    "1tc5jau": [{"ticker": "VEEV", "sentiment": "bullish"}],
    "1tc4rek": [],
    "1tc4g0e": [],
    "1tc4djn": [],
    "1tc3rbr": [],
    "1tc3g9t": [
        {"ticker": "MU", "sentiment": "bearish"},
        {"ticker": "INTC", "sentiment": "bearish"},
    ],
    "1tc36uq": [{"ticker": "RYCEY", "sentiment": "bullish"}],
    "1tc363r": [],
    "1tc2t1s": [{"ticker": "MSFT", "sentiment": "bullish"}],
    "1tc2i5g": [],
    "1tc2c9n": [{"ticker": "ASIC", "sentiment": "bullish"}],
    "1tc2bly": [{"ticker": "FISV", "sentiment": "bearish"}],
    "1tc1skl": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tc0uop": [],
    "1tc0tqm": [{"ticker": "ABT", "sentiment": "bullish"}],
    "1tc0k0v": [],
    "1tbzttu": [
        {"ticker": "MSFT", "sentiment": "bullish"},
        {"ticker": "SPOT", "sentiment": "bullish"},
        {"ticker": "NFLX", "sentiment": "bullish"},
        {"ticker": "APP", "sentiment": "bullish"},
    ],
    "1tbzn8l": [],
    "1tbyh4l": [{"ticker": "EPAM", "sentiment": "bearish"}],
    "1tbwwan": [{"ticker": "CHTR", "sentiment": "bullish"}],
    "1tbux1o": [{"ticker": "MU", "sentiment": "bearish"}],
    "1tbupph": [{"ticker": "HRMY", "sentiment": "bullish"}],
    "1tbtses": [],
    "1tbtfyu": [{"ticker": "UNH", "sentiment": "bullish"}],
    "1tbsngp": [],
    "1tbrdoj": [],
    "1tbqdpy": [{"ticker": "CELH", "sentiment": "bullish"}],
    "1tbo3n7": [],
    "1tbo2sm": [],
    "1tbhaqu": [{"ticker": "WEN", "sentiment": "bullish"}],
    "1tbg9cz": [{"ticker": "DASH", "sentiment": "bullish"}],
    "1tbfp7v": [],
    "1tbfibp": [],
    "1tbewn2": [],
    "1tbdire": [],
    "1tbcsnz": [
        {"ticker": "GOOGL", "sentiment": "bullish"},
        {"ticker": "NVDA", "sentiment": "bullish"},
    ],
    "1tbc4wy": [],
    "1tbaxkk": [],
    "1tbaocl": [{"ticker": "GO", "sentiment": "bullish"}],
    "1tbanlq": [],
    "1tb9l16": [{"ticker": "HMR", "sentiment": "bullish"}],
    "1tb9dd1": [{"ticker": "BWEN", "sentiment": "bullish"}],
    "1tb8srj": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tb8g29": [{"ticker": "KOS", "sentiment": "bullish"}],
    # wallstreetbets
    "1tcgnmo": [{"ticker": "MU", "sentiment": "bullish"}],
    "1tcckmt": [
        {"ticker": "MU", "sentiment": "bullish"},
        {"ticker": "SNDK", "sentiment": "bullish"},
    ],
    "1tcchut": [{"ticker": "CSCO", "sentiment": "bullish"}],
    "1tcccie": [],
    "1tcbxtz": [{"ticker": "LULU", "sentiment": "bearish"}],
    "1tcb490": [],
    "1tcay36": [],
    "1tcaxka": [{"ticker": "HUBS", "sentiment": "bullish"}],
    "1tcah8i": [{"ticker": "SOFI", "sentiment": "bullish"}],
    "1tca641": [{"ticker": "SOFI", "sentiment": "bullish"}],
    "1tca5ld": [{"ticker": "GOOGL", "sentiment": "bullish"}],
    "1tc9w58": [{"ticker": "CSCO", "sentiment": "bullish"}],
    "1tc9jzw": [{"ticker": "SIMO", "sentiment": "bullish"}],
    "1tc9ez8": [{"ticker": "SLS", "sentiment": "bullish"}],
    "1tc96vl": [{"ticker": "SKM", "sentiment": "bullish"}],
    "1tc8tbh": [],
    "1tc8qww": [],
    "1tc8jk6": [],
    "1tc8dep": [{"ticker": "NBIS", "sentiment": "bullish"}],
    "1tc8c7l": [{"ticker": "RKLB", "sentiment": "bullish"}],
    "1tc89v6": [{"ticker": "PSMT", "sentiment": "bullish"}],
    "1tc86qc": [],
    "1tc81sz": [{"ticker": "PLNT", "sentiment": "bullish"}],
    "1tc7pd4": [{"ticker": "NVDA", "sentiment": "bullish"}],
    "1tc7p4o": [
        {"ticker": "MU", "sentiment": "bullish"},
        {"ticker": "AMD", "sentiment": "bullish"},
        {"ticker": "INTC", "sentiment": "bullish"},
    ],
    "1tc7ozs": [],
    "1tc7jbq": [{"ticker": "AAOI", "sentiment": "bullish"}],
    "1tc7ef0": [{"ticker": "SLV", "sentiment": "bullish"}],
    "1tc6uy6": [{"ticker": "MBLY", "sentiment": "bullish"}],
    "1tc6tyl": [{"ticker": "SPRY", "sentiment": "bullish"}],
    "1tc6trw": [
        {"ticker": "NVDA", "sentiment": "bullish"},
        {"ticker": "RKLB", "sentiment": "bullish"},
    ],
    "1tc6mu5": [],
    "1tc6m3p": [],
    "1tc6k5m": [],
    "1tc6ck7": [],
    "1tc63or": [{"ticker": "QUCY", "sentiment": "bearish"}],
    "1tc5sw9": [
        {"ticker": "NVDA", "sentiment": "bullish"},
        {"ticker": "RKLB", "sentiment": "bullish"},
    ],
    "1tc5jds": [],
    "1tc5go7": [],
    "1tc5f6c": [],
    "1tc500y": [{"ticker": "BIRD", "sentiment": "bearish"}],
    "1tc4xld": [],
    "1tc4npa": [
        {"ticker": "SOFI", "sentiment": "bearish"},
        {"ticker": "RDDT", "sentiment": "bearish"},
        {"ticker": "HOOD", "sentiment": "bearish"},
    ],
    "1tc4gz7": [{"ticker": "F", "sentiment": "bullish"}],
    "1tc4dkz": [{"ticker": "HIMS", "sentiment": "bullish"}],
    "1tc3zw6": [
        {"ticker": "NBIS", "sentiment": "bullish"},
        {"ticker": "PLTR", "sentiment": "bullish"},
    ],
    "1tc3szi": [],
    "1tc3s3f": [{"ticker": "RKLB", "sentiment": "bullish"}],
    "1tc3qo6": [],
    "1tc3kf2": [],
    "1tc3gfo": [],
    "1tc3cbe": [],
    "1tc37i3": [{"ticker": "NVDA", "sentiment": "bearish"}],
    "1tc2l65": [{"ticker": "UNH", "sentiment": "bullish"}],
    "1tc2hqh": [{"ticker": "FLEX", "sentiment": "bullish"}],
    "1tc2fqo": [],
    "1tc2bgd": [],
    "1tc28b5": [{"ticker": "FLEX", "sentiment": "bullish"}],
    "1tc24cb": [],
    "1tc18b6": [{"ticker": "MBLY", "sentiment": "bullish"}],
    "1tc096e": [],
    "1tc073w": [],
    "1tc02lr": [{"ticker": "PATH", "sentiment": "bullish"}],
    "1tbxups": [{"ticker": "EOSE", "sentiment": "bullish"}],
    "1tbxs6a": [{"ticker": "NBIS", "sentiment": "bullish"}],
    "1tbx8zx": [],
    # options (lines ~460-500)
    "1tb9rv6": [],
    "1tb71hs": [],
    "1tb6mxy": [{"ticker": "AVEX", "sentiment": "bullish"}],
    "1tb6f1y": [],
    "1taztz4": [{"ticker": "VCX", "sentiment": "bearish"}],
    "1tawhxl": [],
    "1tan45e": [],
    "1tan2ie": [],
    "1tam1ir": [],
    "1tajvom": [],
    "1taj8g5": [{"ticker": "MLTX", "sentiment": "bearish"}],
    "1tahh8x": [{"ticker": "RILY", "sentiment": "bullish"}],
    "1tacor1": [],
    "1ta8z76": [],
    "1ta7xkk": [],
    "1ta7600": [],
    "1ta67my": [],
    "1ta5i83": [],
    "1ta1jxo": [],
    "1t9rh62": [],
    "1t9pix3": [],
    "1t9pcna": [],
    "1t9oumv": [],
    "1t9od64": [],
    "1t9iqda": [],
    "1t9cw16": [],
    "1t9bpzw": [],
    "1t983at": [],
    "1t97033": [{"ticker": "ASTS", "sentiment": "bullish"}],
    "1t9390d": [],
    "1t90cnx": [],
    "1t8yek4": [],
    "1t8vxaj": [],
    "1t8t5lc": [],
    "1t8slgp": [],
    "1t8rlc7": [],
    "1t8q01p": [],
    "1t8m4n8": [],
    "1t8bssf": [],
    "1t88lq3": [],
    "1t8893a": [],
    "1t872th": [
        {"ticker": "AMD", "sentiment": "bullish"},
        {"ticker": "MU", "sentiment": "bullish"},
    ],
    "1t85oye": [],
    "1t83a03": [],
    "1t80r86": [],
    "1t7zm7e": [],
    "1t7v0si": [],
    "1t7uxxf": [{"ticker": "MU", "sentiment": "bullish"}],
    "1t7ujke": [],
    "1t7tj4d": [{"ticker": "PLNT", "sentiment": "bullish"}],
    "1t7sj6x": [
        {"ticker": "INTC", "sentiment": "bearish"},
        {"ticker": "AMD", "sentiment": "bearish"},
    ],
    "1t7pasd": [],
    "1t7jp3e": [],
    "1t7ehbj": [],
    "1t7bygv": [],
    "1t781w9": [],
    "1t75653": [],
    "1t753nm": [],
    "1t72lxj": [],
    "1t72fqj": [],
    "1t70x83": [{"ticker": "NET", "sentiment": "bearish"}],
    "1t70mxe": [],
    "1t6yzmt": [{"ticker": "USO", "sentiment": "bearish"}],
    "1t6wl2i": [],
    "1t6uvtb": [],
    "1t6tob5": [],
    "1t6thlp": [],
    "1t6tfxe": [],
    "1t6scws": [],

    # ── lines 501-676 ─────────────────────────────────────────────
    # options (continued)
    "1t6o9m8": [],
    "1t6lq1i": [],
    "1t6jcsx": [],
    "1t6hoom": [],
    "1t6by9g": [],
    "1t6b1yw": [],
    "1t6b0e1": [],
    "1t68m4w": [],
    "1t65c7w": [],
    "1t65buz": [],
    "1t6105y": [],
    "1t5ygq3": [],
    "1t5wvv2": [],
    "1t5vwb2": [],
    "1t5tgmj": [],
    "1t5s1uy": [],
    "1t5ru83": [],
    # smallstreetbets
    "1tcd0ok": [{"ticker": "REI", "sentiment": "bullish"}],
    "1tccx0q": [],
    "1tccw2x": [{"ticker": "CSCO", "sentiment": "bullish"}],
    "1tccb6f": [],
    "1tcc2y7": [],
    "1tcc02g": [],
    "1tcbzyy": [],
    "1tcbrv4": [{"ticker": "PLNT", "sentiment": "bullish"}],
    "1tcbl2x": [],
    "1tcbc73": [],
    "1tca0al": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tc9vdz": [],
    "1tc94md": [],
    "1tc90z3": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tc87zs": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tc7iiq": [],
    "1tc7ag7": [],
    "1tc6iy8": [{"ticker": "FIGR", "sentiment": "bullish"}],
    "1tc6b6g": [{"ticker": "SPCE", "sentiment": "bullish"}],
    "1tc66om": [],
    "1tc5qcu": [],
    "1tc5g2p": [{"ticker": "LWLG", "sentiment": "bullish"}],
    "1tc5bga": [{"ticker": "RKLB", "sentiment": "bullish"}],
    "1tc4sk1": [{"ticker": "SRXH", "sentiment": "bullish"}],
    "1tc4m6y": [],
    "1tc4bxv": [],
    "1tc46fz": [{"ticker": "NVDA", "sentiment": "bullish"}],
    "1tc441w": [{"ticker": "NBIS", "sentiment": "bearish"}],
    "1tc40ii": [{"ticker": "AMD", "sentiment": "bullish"}],
    "1tc3ztz": [{"ticker": "SVCO", "sentiment": "bullish"}],
    "1tc2xjt": [],
    "1tc2uzn": [],
    "1tc2q0i": [],
    "1tc2fti": [{"ticker": "OUST", "sentiment": "bullish"}],
    "1tc2863": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tc20wo": [{"ticker": "NRED", "sentiment": "bullish"}],
    "1tc16bm": [{"ticker": "SLS", "sentiment": "bullish"}],
    # artificial
    "1tc57aw": [],
    "1tc4xis": [],
    "1tc3wfn": [],
    "1tc3gk9": [],
    "1tc2ujv": [],
    "1tc2qre": [],
    "1tc1hq0": [],
    "1tc1570": [],
    "1tc0pig": [],
    "1tc0jiv": [],
    "1tc01wf": [],
    "1tbyfa5": [],
    "1tbwq7l": [],
    "1tbwpk8": [],
    "1tbvjm5": [],
    "1tbvipk": [],
    "1tbti47": [],
    "1tbrxim": [],
    "1tbr449": [],
    "1tbq71j": [],
    "1tbq353": [],
    "1tbplvh": [],
    "1tbnyx2": [],
    "1tbnmxs": [],
    "1tbhvlq": [],
    "1tbgqbb": [],
    "1tbfv6x": [],
    "1tbf0p9": [],
    "1tbe1y3": [],
    "1tbczco": [],
    "1tbb6iu": [],
    "1tbasiz": [],
    "1tbamu3": [],
    "1tb6mna": [],
    "1tb44vc": [],
    # Semiconductors
    "1tazt8t": [],
    "1tawzbb": [],
    "1tatwex": [{"ticker": "MU", "sentiment": "bullish"}],
    "1tasecn": [],
    "1tanpn8": [],
    "1tagfl4": [],
    "1ta9qun": [],
    "1ta8qqy": [],
    "1ta71k2": [],
    "1t9rnxs": [],
    "1t9orrq": [],
    "1t9kp2p": [],
    "1t8tb6z": [],
    "1t8t33n": [],
    "1t8o1fn": [],
    "1t8dpyp": [],
    "1t8daqe": [],
    "1t8cy89": [],
    "1t8cs1l": [],
    "1t8cpxn": [],
    "1t890eb": [],
    "1t852zn": [],
    "1t7ty6l": [],
    "1t7ohcy": [],
    "1t7nziw": [],
    "1t7ljrs": [],
    "1t7khkk": [],
    "1t7h240": [],
    "1t7dwuy": [],
    "1t751p9": [],
    "1t6xmum": [],
    "1t6vbn6": [],
    "1t6puz6": [],
    "1t6o17j": [],
    "1t6l3oo": [],
    "1t6h6kr": [],
    "1t6h4qf": [],
    "1t6578m": [],
    "1t61fbd": [],
    "1t5wo1y": [],
    "1t5pb0p": [],
    "1t5otp4": [],
    "1t5n36s": [],
    "1t5m93h": [],
    "1t5jdts": [],
    "1t4t4pu": [],
    "1t4fe4i": [],
    "1t4a35l": [],
    "1t49jmu": [],
    "1t41wup": [],
    "1t404dy": [],
    # energy
    "1tc0w8b": [],
    "1tc06if": [],
    "1tbzqvr": [],
    "1tbzqqz": [],
    "1tbz55g": [],
    "1tbvjb2": [],
    "1tbv64t": [],
    "1tbubxo": [],
    "1tbu8c5": [],
    "1tbrokx": [],
    "1tbptv3": [],
    "1tbldsw": [],
    "1tbhe8c": [],
    "1tbh80d": [],
    "1tb98aq": [],
    "1tb8281": [],
    "1tb4ywg": [],
    "1tb4ban": [],
    "1tb3j2e": [],
    "1tb1dn4": [],
    "1tb15wr": [],
    "1tawyhs": [],
    "1tatozq": [],
    "1tarwyd": [],
    "1tar8m2": [],
    "1tapz65": [],
    "1taolpt": [],
    "1taoald": [],
    "1talvgp": [{"ticker": "TOT", "sentiment": "bullish"}],
    "1tal6tj": [],
    "1taiwmx": [],
    "1tad2uu": [],
    "1tacxp7": [],
    "1tactud": [],
    "1tab9ac": [],
    "1ta89ke": [],
}


def main() -> None:
    lines = FIXTURE.read_text(encoding="utf-8").splitlines()
    entries = [json.loads(l) for l in lines if l.strip()]

    updated = 0
    skipped_seed = 0
    for entry in entries:
        eid = entry["id"]
        if eid in LABELS:
            entry["human_labels"] = LABELS[eid]
            updated += 1
        elif entry.get("source") == "seed":
            skipped_seed += 1  # seeds already have correct labels

    out_lines = [json.dumps(e, ensure_ascii=False) for e in entries]
    FIXTURE.write_text("\n".join(out_lines) + "\n", encoding="utf-8")

    print(f"Done. Updated {updated} entries, preserved {skipped_seed} seeds.")
    print(f"Total entries: {len(entries)}")


if __name__ == "__main__":
    main()
